### ISSUE TITLE
Throwing error from the basic snippet provided in readme

### ISSUE THREAD

**Issue by SurajMeena** [pyporn-san/Multporn#26]
`Between Friends
['Best', 'Blowjob', 'Cunnilingus', 'Lolicon', 'Oral sex', 'Stockings', 'Straight', 'Straight Shota', 'Virgin']
Traceback (most recent call last):
  File "api_test.py", line 12, in <module>
    comic.downloadImages()
AttributeError: 'Multporn' object has no attribute 'downloadImages'`
Where does the error lies ?

**Comment by pyporn-san** [comment]
The ``downloadImages`` method has been renamed to ``downloadContent``. I've updated the README.md to reflect that.
