### ISSUE TITLE
Doesnt handle special characters

### ISSUE THREAD

**Issue by ase1590** [pyporn-san/Multporn#90]
With the name of the following comic, it will only continually overwrite the same s.jpg over and over due to the name of the comic being S.EXpedition

Here is the test code

```
comic = Multporn("https://multporn.net/comics/others/s_expedition")

print(comic)


# Downloads the comic
comic.downloadContent()
```

**Comment by lanruth** [comment]
Fix works, thanks @pyporn-san
Package version from pip is outdated and does not contains last changes
