### ISSUE TITLE
New and Comic page is unsupported

### ISSUE THREAD

**Issue by livy-cl** [pyporn-san/Multporn#91]
### Issue
The current https://multporn.net/new and https://multporn.net/comic is not supported / doesn't work in the Webpage class.

### How to reproduce
```
>>> from multporn import Webpage
>>> page = Webpage("https://multporn.net/new")
>>> print(page.links)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/livy/src/multclient/venv/lib/python3.10/site-packages/multporn/multporn.py", line 330, in links
    "table", "views-view-grid").find_all("strong")]
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by pyporn-san** [comment]
https://multporn.net/comic doesn't exist and is probably a typo for https://multporn.net/comics which works fine.
I fixed the issue with https://multporn.net/new as well. Thank you for raising this issue
