### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by lanruth** [pyporn-san/Multporn#92]
Multporn is not accesable directly for me(blocked by ISP) so i am using proxy. With proxy i need to process cloudflare check before access the site otherwise i get error 403 - access is denied.

At this time script does not support to specify cookie.
What should i do to make it work:
method `get` in `RequestHandler` class
`` response = self.session.get(
            url, timeout=self.timeout, params=params, proxies=getproxies(), **kwargs,
            cookies={'cf_clearance' : 'some_data'}) ``
cf_clearance i set manually after cloudflare check is done

**Comment by pyporn-san** [comment]
I added the `requestsParams` so you can provide your custom arguments to the `session.get()` call. Can you check if this solves your issue
